[dosbox]
machine=pc98
memsize=16

[cpu]
core=normal
cputype=auto

[pc98]
enable pc-98 busmouse

[lua]
enabled=true
hooks=true
autostart=C:/Users/Jose/source/repos/dosbox-x/tools/pc98rev/pc98rev.lua

[autoexec]
@echo off
mount c C:\br1jp\BR1_98
c:
BR.BAT
